### ISSUE TITLE
Failed to build due to mismatched types

### ISSUE THREAD

**Issue by jlb6740** [CraneStation/lightbeam#19]
Hi ... I was attempt to walk through lightbeam's example when I failed to compile:

![image](https://user-images.githubusercontent.com/45402135/54652739-327a0f80-4a75-11e9-8d6f-1a605a80efe4.png)

I compiled with: cargo build --example test

This is a fresh checkout. Are there some requirements I am unaware of for building or is this a real issue?

**Comment by bjorn3** [comment]
You can try using an older nightly eg from the date of the latest commit. It seema dynasm needs to be updated for the latest nightly.

**Comment by eira-fransham** [comment]
Ugh, I've been wanting to get rid of `dynasm` for ages, the only reason I still have it is because getting rid of it would essentially mean writing my own assembler and I want to get all the Wasm spec tests passing first. I'll look into it.

**Comment by eira-fransham** [comment]
The most recent nightly that appears to work is the one from `2018-02-01`. Run `rustup override set nightly-2018-02-01` and it should work. The ideal solution is for this to be fixed in dynasm but I absolutely do not want to get into that right now

**Comment by jlb6740** [comment]
@bjorn3 @Vurich .. Hi, thanks for the suggestion. Dynasm has had a couple of releases since the version that lightbeam is pulling in. Dynasm is at 0.3.1 while lightbeam requests 0.2.3. However while the 0.3.1 Dynasm lib compiles, it in fact seems to not register properly with rust when I try to compile their example. Looks like no version of Dynasm I've tried is working with the latest rustc toolchain. I did try to compile lightbeam using nightly rustc from 2018-02-01 (actually looks like 2018-01-31) but using that compiler leads to other errors warning of experimental features in cranelift-entity such as:

> `crate` in paths is experimental
> inclusive range syntax is experimental

Is the status for lightbeam that it simply doesn't work right now because of it's dependency on dynasm which doesn't compile with the latest rustc toolchain ... and also because of its simultaneous dependency on cranelift which doesn't compile with that older rustc tool chain?

**Comment by eira-fransham** [comment]
The `0.3.x` versions of dynasm, which use a proc macro instead of a plugin, appears to no longer work when put in macros. This is really unfortunate because there's basically no other way to have any amount of abstraction with dynasm - you can't have an instruction determined by a runtime value, for example. This unfortunately means that we'll never compile on the latest nightly until dynasm is replaced.

**Comment by eira-fransham** [comment]
Marking as `wontfix` but I'm going to leave this open until we replace `dynasm` entirely

**Comment by jlb6740** [comment]
Hi @Vurich ... I see. Thanks for the explanation. I was hoping to experiment with lightbeam as a quick and simple code generator for wasm but I guess I will try cranelift/faerie instead. What will you use to replace dynasm?

**Comment by eira-fransham** [comment]
@jlb6740 My intention is to just write my own assembler, I wish that I didn't have to but there's no generic assembler that allows for abstraction in Rust right now - because dynasm's only interface is a macro there's no good way to write code that uses it in an extensible, correct and ergonomic way. Your only option for code-sharing is macros and copy-pasting code. Lightbeam is currently not passing all the spec tests so that work will have to wait until they're passing, unfortunately.

**Comment by eira-fransham** [comment]
@jlb6740 Update: Turns out the problem with dynasm is that I was using `ident`in my `macro_rules` argument and the macro was looking for `tt`, the former captured the element and meant it couldn't be matched as a `tt`. I still want to replace `dynasm` eventually but this means that we can continue using it for now and it works on the latest nightly (the only remaining nightly feature needed is `proc_macro_hygiene`)
